### ISSUE TITLE
Is there any plan to add the training code?

### ISSUE THREAD

**Issue by StancyMiller** [haofanwang/CLIFF#1]
You've made a great progress upon the inference performance of CLIFF.
But I think there's some trick based on SPIN when training the model.
I wonder if you have any plan to release the training code?

**Comment by haofanwang** [comment]
Please refer to [this](https://github.com/huawei-noah/noah-research/issues/96). In this project, I just use CLIFF as a pseudo-GT annotator, I don't have a plan to implement it recently.
