### ISSUE TITLE
I don't see the requirements.txt in this repository

### ISSUE THREAD

**Issue by JosephKKim** [haofanwang/CLIFF#3]
Hi! Thanks for releasing this work public. 
I was trying to test this model on my computer but it seems like requiremets.txt mentioned in README is missing. 
Can you commit the file?

thanks, 
Joseph.

**Comment by haofanwang** [comment]
@JosephKKim Thanks for reminding and I have updated. You can also directly refer to [this](https://github.com/huawei-noah/noah-research/blob/master/CLIFF/requirements.txt).

**Comment by JosephKKim** [comment]
@haofanwang 
Thanks for the fast reply, I can see that you are maintaining two repositories one for the company and this one is your own repository.

Sadly, I found one more missing library in your requirements.txt. 
After installing all packages in requirements.txt, it says that there's no module named pytorch3d. I am working on it. But it would be useful for other users if you indicate this dependency in requirements.txt as well.
+ it seems like conda install pytorch3d -c pytorch3d 
doesn't work any idea?

**Comment by haofanwang** [comment]
I follow the [official install instruction](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md) to install pytorch3d. You may meet some conflicts, but you can find corresponding answers in their issues.

**Comment by JosephKKim** [comment]
okay thanks!

**Comment by JosephKKim** [comment]
FYI, pytorch3d seems like it does not support python version 3.10.
But in README it says to make environment named cliff with python=3.10... 
It seems like the problem.

**Comment by haofanwang** [comment]
Try python 3.9.12, it works for me.

**Comment by JosephKKim** [comment]
okay. I think I've solved pytorch3d using environment with python 3.9 but the problem is in the instruction (README) it is misleading to use python 3.10

plus, there are some minor problems while running the code demo_fit.py
1. you have to change SMPL_MODEL_DIR in constants.py in order to match the directory tree you mentioned in the README.
2. chumpy is missing from requirements.txt

Now, I'm faced with the error occurs from pyrender. Let me open another issue for this error.

Thanks for the fast response!

Joseph.
